version: 2

builds:
  - id: ancla
    main: ./cmd/ancla
    binary: ancla
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/SideQuest-Group/ancla-client/internal/cli.Version={{.Version}}
      - -X github.com/SideQuest-Group/ancla-client/internal/cli.Commit={{.ShortCommit}}

archives:
  - id: default
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "ancla_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

signs:
  - cmd: cosign
    artifacts: checksum
    output: true
    args:
      - sign-blob
      - --yes
      - --bundle=${signature}
      - ${artifact}

sboms:
  - artifacts: archive
    cmd: syft
    args:
      - ${artifact}
      - --output=spdx-json=${document}

brews:
  - name: ancla
    ids:
      - default
    repository:
      owner: SideQuest-Group
      name: ancla-client
    directory: Formula
    homepage: "https://ancla.dev"
    description: "CLI client for the Ancla deployment platform"
    license: "Apache-2.0"
    install: |
      bin.install "ancla"
    test: |
      system "#{bin}/ancla", "version"
    caveats: |
      To update: brew upgrade ancla

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"

release:
  github:
    owner: SideQuest-Group
    name: ancla-client
  replace_existing_artifacts: true
