# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ancla < Formula
  desc "CLI client for the Ancla deployment platform"
  homepage "https://ancla.dev"
  version "1.0.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/SideQuest-Group/ancla-client/releases/download/v1.0.2/ancla_1.0.2_darwin_amd64.tar.gz"
      sha256 "e4c103078f48ad766c5f8404cb08b5a8428f4fb72222e71e2ee25bf6a5707a08"

      define_method(:install) do
        bin.install "ancla"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/SideQuest-Group/ancla-client/releases/download/v1.0.2/ancla_1.0.2_darwin_arm64.tar.gz"
      sha256 "3016ba04b0a4b39591b23207b08bfc8712f60c98e9e7149c3a20c6fd1ea9819f"

      define_method(:install) do
        bin.install "ancla"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/SideQuest-Group/ancla-client/releases/download/v1.0.2/ancla_1.0.2_linux_amd64.tar.gz"
      sha256 "88a504e3286a956d81b73879d50343272cae1b5a764db1a1c7a93d7c0eb7633c"
      define_method(:install) do
        bin.install "ancla"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/SideQuest-Group/ancla-client/releases/download/v1.0.2/ancla_1.0.2_linux_arm64.tar.gz"
      sha256 "fe5102bcfd4ace676da9df79e1745249f0dec30be0397c6862622f0feb4277a5"
      define_method(:install) do
        bin.install "ancla"
      end
    end
  end

  def caveats
    <<~EOS
      To update: brew upgrade ancla
    EOS
  end

  test do
    system "#{bin}/ancla", "version"
  end
end
